server:
  port: 10010

spring:
  datasource:
    url: jdbc:mysql://47.94.162.130/game1-server?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1HE17uZZx3GpUC0c
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL55Dialect
